#cloud-config
users:                          
  - name: ubuntu                
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin        
    shell: /bin/bash            
    ssh_authorized_keys:        
      # Teacher key
      - ssh-key AAAAB3NzaC1yc2EAAAADAQABAAABAQDT+7GJtX+CrjK8wpAKWrddHlEGI7dYL9x/opjyhuexzOVJOOzJgCv5+QIACSdHUDCrdDsIdE9sj9JqvjhBouSCKBG1CeRkOwWCyR/xFq2E0t8XPsHPxkSVI4PdwQFbjnmeBindz/wQtSr6SuoZAn7LaKp6qj0ZRn+DGy5c60SmWDOXRVjLeDA+HU4Byvdtn+tyzJM4ADyng4e6lg3MaYzXk2ZBCDu7sF+HL/DucVsv+T7GXLyPX1k1xzFYEOiMBLAYvBhRZ7KaeSH7Uo1XnPAivwBF6+mirsF9M05LU3Sn2MP2d1ddXNmbZcZcBYgGSMwLKsY6+sT/pMAJq4Hkmug1 aws-key
      # Diego1 Key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDP6tm2+t4uzoUiPX9N0mCHEsfBtMoXaozG0sTEtNZIlEZyABK3F43uuO6wcflZ+Wdy9vZtXAcdWsH3T+kSeAPjcIdWAXKyIf3QK82kkdHRzgj8TWuqymOQqlN8qgi7Big7eSaINAsoMUFw/wIY1ZukQUQEQe4Lnrq+dD4DoSlHBnO3bnyGvpBFFcx7WVppVTZCnIXW1ENWSyEYevvjRVA2MS3m+fTJ/xA+J+KDor135ULqF8D8OPSzyPD98WAY/wqnCnzkh0dGeoMSGFwEV1o61CruWStawz6JWBQpwOH0LE35xa8WKl3B7Ym/+ae92ACHJgJfTQl5B2kmxcYVKyNr aws-key
 
ssh_pwauth: false                
disable_root: false              
package_update: true            
packages:
  - apache2
  - php
  - php-mysql
  - adminer
  - curl
  - wget
 
write_files:
  - path: /var/www/html/info.php
    content: "<?php phpinfo(); ?>"
  - path: /var/www/html/db.php
    content: |
      <html>
      <head></head>
      <body>
      Diese Seite macht eine Abfrage auf die Datenbank. <br />
      Das ausgeführte Query ist: <i>select Host, User from mysql.user;</i><br /><br />
      Das Resultat: <br />
      <?php
      $servername = "172.31.16.202";
      $username = "admin";
      $password = "nettspend";
      $dbname = "mysql";
 
      $conn = new mysqli($servername, $username, $password, $dbname);
      if ($conn->connect_error) {
          die("Connection failed: " . $conn->connect_error);
      }
      $sql = "select Host, User from mysql.user;";
      $result = $conn->query($sql);
      while($row = $result->fetch_assoc()){
          echo("<li>" . $row["Host"] . " / " . $row["User"] . "</li>");
      }
      ?>
      </body>
      </html>
 
runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2